import re
from urllib.parse import urlparse
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import utils
import os

def check_port(url):
    """Url contains port in addr"""
    is_port_presented = False
    port_regex = r"(?:https?://(?:www\.)?)[^/]+:"
    if re.search(port_regex, url, flags = re.IGNORECASE):
        is_port_presented = True
    return is_port_presented

def check_url_shortener(url):
    """Url generated by url-shortener service"""
    is_shortener = False
    domain = utils.extract_domain_without_subdomains(url)
    if domain in utils.URL_SHORTENERS:
        is_shortener = True
    return is_shortener

def check_is_ip_addr(url):
    "Url contains ip addr"
    ip_addr = False
    ip_regex = r"(^|https?://)((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}"
    if re.search(ip_regex, url, flags = re.IGNORECASE):
        ip_addr = True
    return ip_addr

def check_is_at_symbol(url):
    """Url contains '@' symbol"""
    is_at = False
    url_without_protocol = url.split('://')[1]
    domain = url_without_protocol.split('/')[0]
    if "@" in domain:
        if ":" not in domain:
            is_at = True
    return is_at

def check_is_homoglyph(url):
    """Detected homoglyph technique"""
    domain = utils.extract_domain_with_subdomains(url)
    if str.isascii(domain):
        return False
    else:
        for letter in domain:
            if (90 > ord(letter) > 65) or (122 > ord(letter) > 97):
                return True
        return False
    
def check_js_redirect_chain(url):
    """Detected JS redirect chain"""
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--window-size=1920,1080')
    driver = webdriver.Chrome(options = options)
    try:
        driver.get(url)

        initial_url = driver.current_url
        redirect_chain = [initial_url]

        time.sleep(2) 

        max_redirects = 10
        for _ in range(max_redirects):
            current_url = driver.current_url
            if current_url != redirect_chain[-1]:
                redirect_chain.append(current_url)
                time.sleep(1)
            else:
                break

        if len(redirect_chain) > 1:
            print(f"JavaScript redirect chain for {url}:")
            for i, u in enumerate(redirect_chain):
                print(f"  Step {i+1}: {u}")
            return redirect_chain
        else:
            print(f"No significant JavaScript redirects detected for {url}. Final URL: {initial_url}")

        domain = utils.extract_domain_without_path(url)
        screenshot_path = os.path.join(utils.SCREEN_PATH, f"{domain}.png")
        driver.save_screenshot(screenshot_path)

    except Exception as e:
        print(f"Error checking {url} with Selenium: {e}")
    finally:
        driver.quit()

preprocess_functions = [
    check_port, check_url_shortener,
    check_is_ip_addr, check_is_at_symbol,
    check_is_homoglyph
]

def preprocess(url):
    descriptions = []
    is_suspicious = False

    for preprocess_function in preprocess_functions:
        result = preprocess_function(url)
        if result == True:
            is_suspicious = True
            desc = preprocess_function.__doc__
            descriptions.append(desc)
    return is_suspicious, descriptions
